@startuml
class Book
class Recipe
class Properties
class Property
class Files
class File
class UserData

Book *-- Book
Book *-- Recipe
Book *-- Properties
Book : uri

Recipe *-- Files
Recipe *-- Properties
Recipe *-- "1" UserData
Recipe : uri
Recipe : wd

Properties *-- Property
Properties : type

Property : key()
Property : value()
Property : order
Property : propagation

Files *-- File
Files : type

@enduml
