@startuml
class Book
class Recipe
class UserData
class Collection  << (T, orchid) <T> >>
class Object
class Properties 
class Property
class Files
class File


Properties --|> Collection
Files --|> Collection


Book *-- Book
Book *-- Recipe
Book *-- Properties
Book : uri

Recipe *-- Properties
Recipe *-- Files
Recipe *-- "1" UserData
Recipe : uri
Recipe : wd

Collection *-- Object
Collection : type

Object : key()
Object : order
Object : propagation
Object <|-- Property
Object <|-- File


Properties --> Property
Property : value()

Files --> File
File : dir
File : rel

note "Collection is a template class\nFiles and Properties are its instantiation \nwith respectively File and Propery as parameter" as N
@enduml
